#!/usr/bin/with-contenv bash

echo '
***************************************************************
***************************************************************
*                                                             *
*                                                             *
*          This image has been deprecated                     *
*                                                             *
*           Use the multi-arch images at                      *
*                                                             *
*               linuxserver/unifi-controller                  *
*                                                             *
*    https://hub.docker.com/r/linuxserver/unifi-controller    *
*                                                             *
*   https://github.com/linuxserver/docker-unifi-controller    *
*                                                             *
*                                                             *
*                                                             *
***************************************************************
***************************************************************'
